repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 24.1a1
    hooks:
    - id: black
      args: [--config=projects/{{ cookiecutter.repo_name }}/pyproject.toml, projects/{{ cookiecutter.repo_name }}/src/]
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    - id: flake8
      args: [--toml-config=projects/{{ cookiecutter.repo_name }}/pyproject.toml, projects/{{ cookiecutter.repo_name }}/src/]
      additional_dependencies: [Flake8-pyproject]
{% cookiecutter.mypy == 'y' %} 
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        exclude: ^tests/
        args:
          [
            --config=projects/{{ cookiecutter.repo_name }}/pyproject.toml,
          ]
{% endif %}
-   repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
-   repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: [--config=projects/{{ cookiecutter.repo_name }}/pyproject.toml, projects/{{ cookiecutter.repo_name }}/src/]

